events {}

http {
  upstream dashboard {
    server dashboard:5173;
  }

  upstream server {
    server server:8080;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://dashboard;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api {
      proxy_pass http://server;
      proxy_set_header Host $host;
    }

    location /account {
      proxy_pass http://server;
      proxy_set_header Host $host;
    }

    location /connect {
      proxy_pass http://server;
      proxy_set_header Host $host;
    }

    location /.well-known {
      proxy_pass http://server;
      proxy_set_header Host $host;
    }
  }
}
